### ISSUE TITLE
Please add a documentation link to winss.readthedocs.io

### ISSUE THREAD

**Issue by csharmath** [Morgan-Stanley/winss#29]
If this is the correct documentation, pelase add a link to it in the readme
http://winss.readthedocs.io/en/latest/

This cool project is getting noticed / mentioned so it would be nice to add the docs link - https://twitter.com/Taylorb_msft/status/940780612947992576

**Comment by csharmath** [comment]
also here
https://twitter.com/jessfraz/status/940646828873265154

**Comment by keithhendry** [comment]
Done.
